### ISSUE TITLE
Provide grouping view

### ISSUE THREAD

**Issue by clebertsuconic** [irockel/tda#15]
I read thread dumps all the time that will have thousands of threads doing exactly the same.. and they are all idle:

```
"Remoting "g61mps-jhq01_HQ:HQserver:MANAGEMENT" task-16" #3237 prio=5 os_prio=0 tid=0x00007fd7040d6800 nid=0xd097 waiting on condition [0x00007fd655cb9000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005cc27c558> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"Remoting "g61mps-jhq01_HQ:HQserver:MANAGEMENT" task-15" #3236 prio=5 os_prio=0 tid=0x00007fd7042bd000 nid=0xd096 waiting on condition [0x00007fd655dba000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005cc27c558> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

Think of thousands like this.

It would be nice if you could have a view of similar threads...

Group1:
java.lant.thread.State... (and then if you open the thread.. you could open the monitors.. and then the threads itself).

It would be really helpful.. I with I had time to contribute :(

**Comment by irockel** [comment]
You can define your own Groups by using the **Categories** Feature, for your example, you can either use the predefined **Idle Thread Filter** (but you must uncheck "Exclusion Filter") and create a Category which includes this filter.

If you just want to get rid of the idle threads, just activate the **Idle Threads Filter** as **Default Filter**. 

Does this fit your feature request?

I had a documentation for all this, but it was in javahelp format, which is a pain to build. I will try to move this into the github wiki.

**Comment by irockel** [comment]
Added relevant documentation to Wiki:

https://github.com/irockel/tda/wiki/Using-Filters
