### ISSUE TITLE
StringIndexOutOfBoundsException on dump parse

### ISSUE THREAD

**Issue by irockel** [irockel/tda#2]
The following exception can happen while parsing a thread dump:

```
Exception in thread "Thread-3" java.lang.StringIndexOutOfBoundsException: String
 index out of range: -73
        at java.lang.String.substring(Unknown Source)
        at com.pironet.tda.SunJDKParser.getThreadTokens(SunJDKParser.java:698)
        at com.pironet.tda.AbstractDumpParser.addToCategory(AbstractDumpParser.j
ava:221)
        at com.pironet.tda.SunJDKParser.parseNext(SunJDKParser.java:192)
        at com.pironet.tda.SunJDKParser.hasMoreDumps(SunJDKParser.java:73)
        at com.pironet.tda.TDA.addThreadDumps(TDA.java:1099)
        at com.pironet.tda.TDA.access$900(TDA.java:123)
        at com.pironet.tda.TDA$4.construct(TDA.java:703)
        at com.pironet.tda.utils.SwingWorker$2.run(SwingWorker.java:131)
        at java.lang.Thread.run(Unknown Source)

```
This patch fixes it:

```
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- Base (BASE)
+++ Locally Modified (Based On LOCAL)
@@ -1023,7 +1023,7 @@
         if (name.indexOf("prio") > 0) {
             tokens = new String[7];
 
-            tokens[0] = name.substring(1, name.lastIndexOf('"'));
+            tokens[0] = name.substring(1, name.lastIndexOf('"') == 0 ? name.length() - 1 : name.lastIndexOf('"'));           
             tokens[1] = name.indexOf("daemon") > 0 ? "Daemon" : "Task";
 
             String strippedToken = name.substring(name.lastIndexOf('"') + 1);
@@ -1078,16 +1078,19 @@
             }
         } else {
             tokens = new String[3];
-            tokens[0] = name.substring(1, name.lastIndexOf('"'));
+            tokens[0] = name.substring(1, name.lastIndexOf('"') == 0 ? name.length() - 1 : name.lastIndexOf('"'));
             if (name.indexOf("nid=") > 0) {
                 tokens[1] = name.substring(name.indexOf("nid=") + 4, name.indexOf("state=") - 1);
                 tokens[2] = name.substring(name.indexOf("state=") + 6);
             } else if (name.indexOf("t@") > 0) {
                 tokens[1] = name.substring(name.indexOf("t@") + 2, name.indexOf("state=") - 1);
                 tokens[2] = name.substring(name.indexOf("state=") + 6);
-            } else {
+            } else if (name.indexOf("id=") > 0) {
                 tokens[1] = name.substring(name.indexOf("id=") + 3, name.indexOf(" in"));
                 tokens[2] = name.substring(name.indexOf(" in") + 3);
+            } else {
+                tokens[1] = "";
+                tokens[2] = "";
             }
         }

```

**Comment by irockel** [comment]
Applied patch.
